services:
  - type: web
    name: frete-api-java
    env: docker
    plan: free
    rootDir: frete-api-java
    dockerfilePath: frete-api-java/Dockerfile
    autoDeploy: true
    envVars:
      - key: JAVA_OPTS
        value: "-Xmx512m"
      - key: PORT
        value: "8080"
