# Arquivo: render.yaml
services:
  - type: web
    name: gabrielly-frete-api
    runtime: docker # CORRIGIDO: Usa 'runtime' em vez de 'env'
    plan: starter # ALTERADO: Free pode ser muito limitado para Docker. Use Starter ($7/mês).
    rootDir: frete-api-java
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: JAVA_OPTS
        value: "-Xmx384m"
      - key: PORT
        value: "8080"