# Arquivo render.yaml - Configuração CORRIGIDA (Versão Final)

# A seção 'databases' define os bancos de dados
databases:
  - name: gabrielly-db
    plan: free

# A seção 'services' define os serviços web e estáticos
services:
  # 1. BACKEND NODE.JS (API Principal + Chatbot + Email)
  - type: web
    name: gabrielly-backend-node
    runtime: node
    region: oregon
    plan: free
    # Se você executa os comandos na raiz do repositório
    buildCommand: cd gabrielly-backend && npm install
    startCommand: cd gabrielly-backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      # Configuração da string de conexão do banco de dados
      - key: DATABASE_URL
        fromDatabase:
          name: gabrielly-db
          property: connectionString
      # Variáveis de ambiente extras
      - key: DB_HOST
        fromDatabase:
          name: gabrielly-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: gabrielly-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: gabrielly-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: gabrielly-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: gabrielly-db
          property: password
      # Variáveis de ambiente que DEVEM SER DEFINIDAS NO PAINEL DO RENDER.
      - key: OPENAI_API_KEY
        value: "" # Placeholder, valor será definido no painel do Render
      - key: EMAIL_USER
        value: "" # Placeholder, valor será definido no painel do Render
      - key: EMAIL_PASS
        value: "" # Placeholder, valor será definido no painel do Render
      - key: LOJISTA_EMAIL
        value: "" # Placeholder, valor será definido no painel do Render
      - key: REACT_APP_API_URL
        value: "" # Placeholder, valor será definido no painel do Render

  # 2. BACKEND JAVA (API Frete) - Spring Boot
  - type: web
    name: gabrielly-frete-api
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./frete-api-java/Dockerfile
    dockerContext: ./frete-api-java
    envVars:
      - key: PORT
        value: "8080"
      - key: JAVA_OPTS
        value: "-Xmx512m -Xms256m"
      - key: SPRING_PROFILES_ACTIVE
        value: production

  # 3. FRONTEND REACT (SPA) - SITE ESTÁTICO
  # MUDANÇA CRÍTICA: type deve ser 'static_site'
  - type: static_site # CORRIGIDO: Este é o tipo correto para Render Blueprints
    name: gabrielly-frontend
    # Campos como runtime, region e plan SÃO REMOVIDOS para type: static_site
    buildCommand: cd gabrielly-frontend && npm install && npm run build
    staticPublishPath: gabrielly-frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://gabrielly-backend-node.onrender.com
      - key: REACT_APP_FRETE_API_URL
        value: https://gabrielly-frete-api.onrender.com